
target: quality
test_size: 0.2
rf_hp:
  n_estimators: [50, 100, 200, 500, 1000]
  max_depth: [5, 10, 20, 50, 100, null]
  max_features: [1.0, "sqrt", "log2", null]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]
catboost_hp:
  iterations: [100, 250, 500, 1000]
  depth: [4, 6, 8, 10]
  learning_rate: [0.01, 0.05, 0.1, 0.2]
  l2_leaf_reg: [1, 3, 5, 7, 9]
optimization:
  init_points: 10
  n_iter: 50
cross_validation:
  n_splits: 5
